name: Regenerate content index

on:
  push:
    branches: [ master, main ]
    paths:
      - 'content/**'
      - 'generate-index.js'

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run generator
        run: node generate-index.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content/index.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: regenerate content/index.json [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
